all: brute greedy match

brute:
	g++ -std=c++11 -o brute brute.cpp

greedy:
	g++ -std=c++11 -o greedy greedy.cpp

match:
	g++ -std=c++11 -o match match.cpp

floyd:
	g++ -std=c++11 -o floyd floyd.cpp

ramsey:
	g++ -std=c++11 -o ramsey ramsey.cpp

reads:
	g++ -std=c++11 -o reads reads.cpp

clean:
	rm -rf brute greedy match floyd ramsey reads
